const b = 56

try {
    b = 68
} catch (error) {
    console.log(error)
}